/* code-rookie companion — static SPA. Zero runtime dependencies.
 * Renders from window.CODE_ROOKIE_DATA (generated by build/parse.mjs).
 * All student state is local (localStorage); nothing leaves the machine. */

(function () {
  'use strict';

  const DATA = window.CODE_ROOKIE_DATA;
  if (!DATA) {
    document.getElementById('main').innerHTML =
      '<div class="wrap"><h1 class="page-title">No content built</h1>' +
      '<p class="page-sub">Run <code>npm run build</code> in <code>companion/</code> to generate <code>content.js</code>.</p></div>';
    return;
  }

  const GUIDES = DATA.guides;
  const guideBySlug = Object.fromEntries(GUIDES.map((g) => [g.slug, g]));

  // XP weights.
  const XP = { section: 10, quizGot: 5, reflection: 20, moduleComplete: 50 };

  // ---------- persistence ----------
  const STORE_KEY = 'coderookie.v1';
  function loadStore() {
    try {
      const s = JSON.parse(localStorage.getItem(STORE_KEY) || '{}');
      s.version = 1;
      s.modules = s.modules || {};
      s.activeDays = s.activeDays || [];
      s.history = s.history || {}; // per-guide historical-context quiz marks (companion/ layer)
      return s;
    } catch {
      return { version: 1, modules: {}, activeDays: [], history: {} };
    }
  }
  function historyState(slug) {
    if (!store.history[slug]) store.history[slug] = { qa: {} };
    return store.history[slug];
  }
  let store = loadStore();
  function saveStore() {
    try { localStorage.setItem(STORE_KEY, JSON.stringify(store)); } catch {}
  }
  function todayISO() { return new Date().toISOString().slice(0, 10); }
  function markActiveToday() {
    const t = todayISO();
    if (!store.activeDays.includes(t)) store.activeDays.push(t);
  }
  function mkey(slug, file) { return slug + '|' + file; }
  function moduleState(slug, file) {
    const k = mkey(slug, file);
    if (!store.modules[k]) {
      store.modules[k] = { sections: {}, quiz: {}, practice: {}, reflection: null, capstoneNote: '', timeMs: 0, completed: false };
    }
    return store.modules[k];
  }

  // ---------- derived stats ----------
  function totalXP() {
    let xp = 0;
    for (const g of GUIDES) {
      for (const m of g.modules) {
        const st = store.modules[mkey(g.slug, m.file)];
        if (!st) continue;
        xp += Object.values(st.sections).filter(Boolean).length * XP.section;
        xp += Object.values(st.quiz).filter((v) => v === 'got').length * XP.quizGot;
        if (st.reflection && st.reflection.savedAt) xp += XP.reflection;
        if (st.completed) xp += XP.moduleComplete;
      }
    }
    return xp;
  }
  function level(xp) { return Math.floor(xp / 250) + 1; }
  function computeStreak() {
    const set = new Set(store.activeDays);
    const d = new Date();
    if (!set.has(todayISO())) d.setDate(d.getDate() - 1); // grace: streak can end yesterday
    let streak = 0;
    for (;;) {
      const k = d.toISOString().slice(0, 10);
      if (set.has(k)) { streak++; d.setDate(d.getDate() - 1); } else break;
    }
    return streak;
  }
  function guideProgress(g) {
    const total = g.modules.length;
    const done = g.modules.filter((m) => store.modules[mkey(g.slug, m.file)]?.completed).length;
    return { done, total, pct: total ? Math.round((done / total) * 100) : 0 };
  }

  // ---------- tiny helpers ----------
  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
  // minimal inline markdown for short extracted strings (code + bold + links)
  function inlineMd(s) {
    let out = esc(s);
    out = out.replace(/`([^`]+)`/g, (_, c) => '<code>' + c + '</code>');
    out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    out = out.replace(/\[([^\]]+)\]\((https?:[^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>');
    return out;
  }
  function shortLang(g) { return (g.title.split('—')[0] || g.slug).trim(); }
  function moduleLabel(m) {
    if (m.kind === 'assessment') return 'the Final Assessment';
    return 'Module ' + m.moduleNumber + ' — ' + m.title;
  }

  // ---------- toast + modal ----------
  let toastTimer = null;
  function toast(msg) {
    let el = document.querySelector('.toast');
    if (!el) { el = document.createElement('div'); el.className = 'toast'; document.body.appendChild(el); }
    el.textContent = msg;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => el.remove(), 2200);
  }
  function closeModal() { document.getElementById('modal-root').innerHTML = ''; }
  function openPromptModal(promptText) {
    const root = document.getElementById('modal-root');
    root.innerHTML =
      '<div class="modal-back" data-action="modal-backdrop">' +
      '<div class="modal">' +
      '<h3>🧭 Coaching prompt</h3>' +
      '<p class="modal-hint">Paste this into your preferred coding LLM. It asks the model to coach you Socratically — questions, not answers. Edit anything before you send it.</p>' +
      '<textarea id="prompt-text" spellcheck="false">' + esc(promptText) + '</textarea>' +
      '<div class="modal-actions">' +
      '<button class="btn ghost" data-action="close-modal">Close</button>' +
      '<button class="btn primary" data-action="copy-prompt">Copy to clipboard</button>' +
      '</div></div></div>';
    // best-effort auto copy
    tryClipboard(promptText);
    const ta = document.getElementById('prompt-text');
    ta.focus(); ta.setSelectionRange(0, 0);
  }
  function tryClipboard(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(() => toast('Copied — paste into your LLM')).catch(() => {});
    }
  }

  // ---------- Socratic prompt fill ----------
  function buildPrompt(g, m, section, objective, task) {
    const sectionClause = section ? ', in the section “' + section + '”' : '';
    return DATA.socraticPrompt
      .replace(/\{\{language\}\}/g, shortLang(g))
      .replace(/\{\{guideTitle\}\}/g, g.title)
      .replace(/\{\{module\}\}/g, moduleLabel(m))
      .replace(/\{\{sectionClause\}\}/g, sectionClause)
      .replace(/\{\{objective\}\}/g, objective || 'this topic')
      .replace(/\{\{task\}\}/g, task || m.title)
      .replace(/\{\{answerNote\}\}/g, '')
      .trim();
  }
  // Same template, filled from the companion/ historical-context layer instead of
  // a module's own objective/task — there is no single "module" for this, so the
  // template's {{module}} slot gets a plain label instead of moduleLabel(m).
  function buildHistoryPrompt(g) {
    const c = g.companion;
    const task = c.reflectionPrompts.length
      ? 'Specifically, work through these with me one at a time:\n' + c.reflectionPrompts.map((p, i) => (i + 1) + '. ' + p).join('\n')
      : 'Walk me through where this language actually came from and what problem it was a response to.';
    return DATA.socraticPrompt
      .replace(/\{\{language\}\}/g, shortLang(g))
      .replace(/\{\{guideTitle\}\}/g, g.title)
      .replace(/\{\{module\}\}/g, 'its historical context')
      .replace(/\{\{sectionClause\}\}/g, '')
      .replace(/\{\{objective\}\}/g, 'why this language exists, what came before it, and what it was reacting to')
      .replace(/\{\{task\}\}/g, task)
      .replace(/\{\{answerNote\}\}/g, '')
      .trim();
  }

  // ---------- router ----------
  function parseHash() {
    const h = location.hash.replace(/^#\/?/, '');
    const parts = h.split('/').filter(Boolean).map(decodeURIComponent);
    if (parts.length === 0) return { view: 'home' };
    if (parts[0] === 'threads') return { view: 'threads' };
    if (parts[0] === 'portfolio') return { view: 'portfolio' };
    if (parts[0] === 'history') return { view: 'history', slug: parts[1] || '00-overview' };
    if (parts[0] === 'appendix') return { view: 'appendix', slug: parts[1] || '00-overview' };
    if (parts[0] === 'guide' && parts[1]) {
      if (parts[2] === 'module' && parts[3]) return { view: 'module', slug: parts[1], file: parts[3] };
      return { view: 'guide', slug: parts[1] };
    }
    return { view: 'home' };
  }
  function go(hash) { location.hash = hash; }

  // ---------- time tracking ----------
  let timeTimer = null;
  let activeModuleKey = null;
  function startTimer(slug, file) {
    stopTimer();
    activeModuleKey = mkey(slug, file);
    const st = moduleState(slug, file);
    if (!st.startedAt) st.startedAt = new Date().toISOString();
    let sinceSave = 0;
    timeTimer = setInterval(() => {
      if (document.visibilityState !== 'visible') return;
      st.timeMs += 10000;
      sinceSave += 10000;
      if (sinceSave >= 30000) { saveStore(); sinceSave = 0; renderStats(); }
    }, 10000);
  }
  function stopTimer() {
    if (timeTimer) { clearInterval(timeTimer); timeTimer = null; saveStore(); }
    activeModuleKey = null;
  }
  function fmtTime(ms) {
    const min = Math.round(ms / 60000);
    if (min < 60) return min + 'm';
    return Math.floor(min / 60) + 'h ' + (min % 60) + 'm';
  }

  // ---------- draft reflection (survives re-render) ----------
  let draft = {};
  let draftKey = null; // only re-init the draft when the active module changes
  function initDraft(st) {
    const base = st.reflection || {};
    draft = {};
    for (const p of DATA.reflection.prompts) draft[p.id] = base[p.id] || '';
    for (const r of DATA.reflection.ratings) draft[r.id] = base[r.id] || 0;
  }

  // ================= RENDER =================

  function renderStats() {
    const xp = totalXP();
    const el = document.getElementById('stats');
    el.innerHTML =
      '<span class="stat xp"><span class="ic">✦</span>Lvl <b>' + level(xp) + '</b></span>' +
      '<span class="stat xp"><b>' + xp + '</b>&nbsp;XP</span>' +
      '<span class="stat streak"><span class="ic">🔥</span><b>' + computeStreak() + '</b>&nbsp;day</span>' +
      '<button class="btn small ghost" data-nav="portfolio">Portfolio</button>';
  }

  function renderSidebar(route) {
    const sb = document.getElementById('sidebar');
    let html = '<div class="side-section-title">Pathway</div>';
    for (const g of GUIDES) {
      const p = guideProgress(g);
      const activeGuide = (route.slug === g.slug);
      html += '<div class="guide-item ' + (activeGuide ? 'active' : '') + '" data-guide="' + g.slug + '">' +
        '<div class="g-title">' + esc(shortLang(g)) + '</div>' +
        '<div class="g-meta">' + p.done + '/' + p.total + ' modules · ' + p.pct + '%</div>' +
        '<div class="guide-progress"><i style="width:' + p.pct + '%"></i></div></div>';
      if (activeGuide) {
        html += '<div class="module-list">';
        for (const m of g.modules) {
          const st = store.modules[mkey(g.slug, m.file)];
          const done = st?.completed;
          const activeM = (route.view === 'module' && route.file === m.file);
          html += '<div class="module-item ' + (done ? 'done' : '') + ' ' + (m.kind === 'assessment' ? 'assessment' : '') + ' ' +
            (activeM ? 'active' : '') + '" data-module="' + g.slug + '|' + esc(m.file) + '">' +
            '<span class="m-check">' + (done ? '✓' : '') + '</span>' +
            '<span class="m-num">' + (m.kind === 'assessment' ? '★' : m.moduleNumber) + '</span>' +
            '<span class="m-title">' + esc(m.title) + '</span></div>';
        }
        html += '</div>';
      }
    }
    html += '<div class="side-section-title">Explore</div>';
    html += '<div class="nav-link" data-nav="threads">🧵 Cross-language threads</div>';
    html += '<div class="nav-link" data-nav="history">📜 History of Computing</div>';
    html += '<div class="nav-link" data-nav="appendix">🔌 AI Orchestration Appendix</div>';
    html += '<div class="nav-link" data-nav="portfolio">🎓 My portfolio</div>';
    sb.innerHTML = html;
  }

  function renderHome() {
    const xp = totalXP();
    let cards = '';
    for (const g of GUIDES) {
      const p = guideProgress(g);
      cards += '<div class="gcard" data-guide="' + g.slug + '">' +
        '<h3>' + esc(shortLang(g)) + '</h3>' +
        '<p>' + esc(g.promise ? truncate(g.promise, 130) : g.title) + '</p>' +
        '<div class="g-foot"><span>' + g.modules.length + ' modules</span><span>' + p.pct + '% complete</span></div>' +
        '<div class="guide-progress" style="margin-top:8px"><i style="width:' + p.pct + '%"></i></div></div>';
    }
    const badges = earnedBadges();
    const main = document.getElementById('main');
    main.innerHTML =
      '<div class="wrap">' +
      '<h1 class="page-title">A polyglot survey of where languages come from</h1>' +
      '<p class="page-sub">Read, run the code in <em>your own</em> editor, get coached by <em>your own</em> LLM — Socratically, not spoon-fed — reflect, and walk away with a portfolio and a sense of which language fits you. Not a certificate. Self-awareness.</p>' +
      '<div style="margin:6px 0 22px"><span class="stat xp"><b>' + xp + '</b>&nbsp;XP · Level ' + level(xp) + '</span> ' +
        '<span class="stat streak">🔥 <b>' + computeStreak() + '</b> day streak</span></div>' +
      '<div class="gcard" data-nav="history" style="margin-bottom:26px;border-color:var(--accent-dim,#3a3f52)">' +
        '<h3>📜 History of Computing — start here for the big picture</h3>' +
        '<p>Babbage to the Transformer, seven eras. Not required before you dive into a language below — every guide links out to the relevant era right where it matters — but if you want the whole story first, this is it.</p></div>' +
      '<h2 style="font-size:16px;color:var(--text-dim);margin:0 0 12px">This pathway</h2>' +
      '<div class="card-grid">' + cards + '</div>' +
      '<h2 style="font-size:16px;color:var(--text-dim);margin:26px 0 12px">Beyond the pathway</h2>' +
      '<div class="card-grid">' +
        '<div class="gcard" data-nav="threads"><h3>🧵 Cross-language threads</h3>' +
        '<p>The same idea, traced across languages and decades — what makes this a survey, not a stack of unrelated courses.</p></div>' +
        '<div class="gcard" data-nav="appendix"><h3>🔌 AI Orchestration Appendix</h3>' +
        '<p>LangChain, LangGraph, n8n — and the 2025–2026 shift into harness, context, and skills. Dated the day it was written.</p></div>' +
      '</div>' +
      '<div class="panel" style="margin-top:26px"><h3 class="panel-title">🏅 Badges</h3>' +
        (badges.length ? '<div class="badges">' + badges.map((b) => '<span class="badge">' + esc(b) + '</span>').join('') + '</div>'
          : '<p class="empty">Complete a module to earn your first badge.</p>') +
      '</div>' +
      '<div class="panel"><h3 class="panel-title">🧭 How this works</h3>' +
        '<p class="panel-hint" style="margin:0">Each section has a <b>Coach me</b> button — it hands you a ready-made Socratic prompt for your LLM (it will ask you questions, not write your code). Capstones are your boss levels: build them in your own repo. Reflect as you go; export your portfolio anytime from the top-right.</p></div>' +
      '</div>';
  }
  function truncate(s, n) { return s.length > n ? s.slice(0, n - 1).trim() + '…' : s; }

  function earnedBadges() {
    const out = [];
    for (const g of GUIDES) {
      const p = guideProgress(g);
      if (p.done === p.total && p.total > 0) out.push(shortLang(g) + ' ✓ complete');
      else if (p.done > 0) out.push(shortLang(g) + ': ' + p.done + ' modules');
    }
    return out;
  }

  // The companion/ historical-context layer: founding paper, historical note,
  // cross-thread connection, a Socratic coach prompt, and self-graded short-answer
  // flip cards. Rendered once per guide (not per module) — modules that have a
  // specific companion link just point back here (see renderModule).
  function renderHistoryPanel(g) {
    const c = g.companion;
    if (!c) return '';
    const hst = historyState(g.slug);
    const qa = c.shortAnswer.map((q) => {
      const mark = hst.qa[q.n];
      return '<div class="flip ' + (mark === 'got' ? 'got' : mark === 'review' ? 'review' : '') + '" data-n="' + q.n + '">' +
        '<div class="q"><span class="qn">' + q.n + '</span>' + q.qHtml + '</div>' +
        '<div class="a hidden">' + q.aHtml + '</div>' +
        '<div class="flip-actions">' +
        '<button class="btn small reveal" data-action="flip-history" data-n="' + q.n + '">Reveal answer</button>' +
        '<button class="btn small" data-action="mark-quiz-history" data-slug="' + g.slug + '" data-n="' + q.n + '" data-val="got">✓ Got it</button>' +
        '<button class="btn small" data-action="mark-quiz-history" data-slug="' + g.slug + '" data-n="' + q.n + '" data-val="review">↻ Review</button>' +
        '</div></div>';
    }).join('');
    const links = c.links.length
      ? '<p class="panel-hint" style="margin-top:14px"><b>Where this shows up in the guide:</b></p>' +
        c.links.map((l) => {
          const isThisGuide = l.slug === g.slug;
          const target = isThisGuide ? '<a data-module="' + g.slug + '|' + esc(l.file) + '">' + esc(l.ref) + '</a>' : esc(l.ref);
          return '<div class="coach-row"><div class="cr-text"><span class="cr-tag">' + target + '</span>' + inlineMd(l.description) + '</div></div>';
        }).join('')
      : '';
    return '<div class="panel"><h3 class="panel-title">📜 Historical context</h3>' +
      '<div class="content">' + c.foundingHtml + c.historicalHtml + '</div>' +
      '<div class="coach-row"><div class="cr-text"><span class="cr-tag">History</span>Coach me through where this language actually came from and what it was reacting to.</div>' +
      '<button class="btn small" data-action="coach-history" data-slug="' + g.slug + '">🧭 Coach me</button></div>' +
      (qa ? '<p class="panel-hint" style="margin-top:14px">Self-graded, same as the module quizzes.</p><div class="quiz-grid">' + qa + '</div>' : '') +
      (c.crossThreadHtml ? '<div class="content" style="margin-top:14px">' + c.crossThreadHtml + '</div>' : '') +
      links +
      '</div>';
  }

  function renderGuide(slug) {
    const g = guideBySlug[slug];
    if (!g) return renderHome();
    const p = guideProgress(g);
    let mods = '';
    for (const m of g.modules) {
      const st = store.modules[mkey(g.slug, m.file)];
      mods += '<div class="module-item ' + (st?.completed ? 'done' : '') + '" data-module="' + g.slug + '|' + esc(m.file) + '" style="font-size:14.5px;padding:10px 12px">' +
        '<span class="m-check">' + (st?.completed ? '✓' : '') + '</span>' +
        '<span class="m-num">' + (m.kind === 'assessment' ? '★' : m.moduleNumber) + '</span>' +
        '<span class="m-title">' + esc(m.title) + '</span>' +
        (m.companionLinks?.length ? '<span class="pill" style="margin-left:6px">📜</span>' : '') +
        (st?.timeMs ? '<span class="self-mark">' + fmtTime(st.timeMs) + '</span>' : '') +
        '</div>';
    }
    const setup = g.setupDocUrl
      ? '<a class="btn small" href="' + esc(g.setupDocUrl) + '" target="_blank" rel="noopener">⚙ Environment setup</a>'
      : '<span class="pill">⚙ Environment setup — link to be added</span>';
    let capstones = '';
    if (g.overview?.capstones?.rows?.length) {
      capstones = '<div class="panel"><h3 class="panel-title">👾 Capstones (your boss levels)</h3>' +
        '<p class="panel-hint">Build these in your own repo — they become the folders of your portfolio.</p>' +
        g.overview.capstones.rows.map((r) => '<div class="coach-row"><div class="cr-text"><span class="cr-tag">Capstone ' + esc(r[0]) + (r[r.length - 1] ? ' · ' + esc(r[r.length - 1]) : '') + '</span>' + inlineMd(r[1] || '') + '</div></div>').join('') +
        '</div>';
    }
    document.getElementById('main').innerHTML =
      '<div class="wrap">' +
      '<div class="crumbs"><a data-nav="home">Home</a> / ' + esc(shortLang(g)) + '</div>' +
      '<h1 class="page-title">' + esc(g.title) + '</h1>' +
      (g.promise ? '<p class="page-sub">' + esc(g.promise) + '</p>' : '') +
      '<div style="margin-bottom:16px">' + setup +
        ' <span class="pill green">' + p.pct + '% complete</span>' +
        (g.toolchain ? ' <span class="pill">' + esc(truncate(g.toolchain, 60)) + '</span>' : '') + '</div>' +
      '<div class="panel"><h3 class="panel-title">Modules</h3>' + mods + '</div>' +
      capstones +
      renderHistoryPanel(g) +
      '</div>';
  }

  function renderModule(slug, file) {
    const g = guideBySlug[slug];
    const m = g && g.modules.find((x) => x.file === file);
    if (!m) return renderHome();
    const st = moduleState(slug, file);
    const dkey = mkey(slug, file);
    if (draftKey !== dkey) { initDraft(st); draftKey = dkey; }
    startTimer(slug, file);

    // coaching rows: general + per practice + per pitfall
    let coachRows =
      '<div class="coach-row"><div class="cr-text"><span class="cr-tag">Whole module</span>' +
      'Coach me through the ideas in this module.</div>' +
      '<button class="btn small" data-action="coach" data-kind="module" data-idx="-1">🧭 Coach me</button></div>';
    m.practice.forEach((pr, i) => {
      coachRows += '<div class="coach-row"><div class="cr-text"><span class="cr-tag">Practice · ' + esc(pr.section) + '</span>' + inlineMd(pr.text) + '</div>' +
        '<label class="coach-check"><input type="checkbox" data-action="toggle-practice" data-idx="' + i + '" ' + (st.practice[i] ? 'checked' : '') + '/> did it</label>' +
        '<button class="btn small" data-action="coach" data-kind="practice" data-idx="' + i + '">🧭 Coach me</button></div>';
    });
    m.pitfalls.forEach((pf, i) => {
      coachRows += '<div class="coach-row gotcha"><div class="cr-text"><span class="cr-tag">Gotcha · ' + esc(pf.section) + '</span>' + inlineMd(truncate(pf.text, 220)) + '</div>' +
        '<button class="btn small" data-action="coach" data-kind="pitfall" data-idx="' + i + '">🧭 Coach me</button></div>';
    });

    // quiz flip cards
    let quiz = '';
    if (m.quiz.length) {
      quiz = m.quiz.map((q) => {
        const mark = st.quiz[q.n];
        return '<div class="flip ' + (mark === 'got' ? 'got' : mark === 'review' ? 'review' : '') + '" data-n="' + q.n + '">' +
          '<div class="q"><span class="qn">' + q.n + '</span>' + q.qHtml.replace(/^<p>|<\/p>$/g, '') + '</div>' +
          '<div class="a hidden">' + (q.aHtml || '<em>No answer recorded.</em>') + '</div>' +
          '<div class="flip-actions">' +
          '<button class="btn small reveal" data-action="flip" data-n="' + q.n + '">Reveal answer</button>' +
          '<button class="btn small" data-action="mark-quiz" data-n="' + q.n + '" data-val="got">✓ Got it</button>' +
          '<button class="btn small" data-action="mark-quiz" data-n="' + q.n + '" data-val="review">↻ Review</button>' +
          '</div></div>';
      }).join('');
      quiz = '<div class="panel"><h3 class="panel-title">🃏 ' + (m.kind === 'assessment' ? 'Final assessment' : 'Progress check') +
        ' <span class="pill">self-graded</span></h3>' +
        '<p class="panel-hint">Answer in your head (or your editor) first, then reveal. Mark yourself honestly — this is for you.</p>' +
        '<div class="quiz-grid">' + quiz + '</div></div>';
    }

    // reflection card
    let refl = '';
    if (m.kind !== 'assessment') {
      refl = '<div class="panel"><h3 class="panel-title">📓 Reflection ' +
        (st.reflection?.savedAt ? '<span class="pill green">saved</span>' : '<span class="pill">optional</span>') + '</h3>' +
        '<p class="panel-hint">A minute of honesty here is what your final portfolio report is built from.</p>' +
        DATA.reflection.prompts.map((pmt) =>
          '<div class="reflect-field"><label>' + esc(pmt.label) + '</label>' +
          '<textarea class="' + (pmt.long ? 'long' : '') + '" data-refl="' + pmt.id + '" placeholder="' + esc(pmt.placeholder || '') + '">' + esc(draft[pmt.id] || '') + '</textarea></div>'
        ).join('') +
        '<div class="rating-row">' + DATA.reflection.ratings.map((r) => renderRating(r)).join('') + '</div>' +
        '<div class="save-row"><button class="btn primary" data-action="save-reflection">Save reflection (+' + XP.reflection + ' XP)</button>' +
        (st.reflection?.savedAt ? '<span class="saved-note">Last saved ' + new Date(st.reflection.savedAt).toLocaleString() + '</span>' : '') +
        '</div></div>';
    }

    // capstone note (only if this guide has capstones)
    let capNote = '';
    if (g.overview?.capstones?.rows?.length) {
      capNote = '<div class="panel"><h3 class="panel-title">👾 Capstone artifact</h3>' +
        '<p class="panel-hint">Building a capstone for this guide? Note what you made and where (a repo path / commit). It goes into your portfolio.</p>' +
        '<div class="reflect-field"><textarea class="long" data-capstone placeholder="e.g. 6502-asm/capstone-3-monitor — keypad in, memory write, echo back. Runs under sim65.">' + esc(st.capstoneNote || '') + '</textarea></div>' +
        '<button class="btn" data-action="save-capstone">Save note</button></div>';
    }

    const objectivesList = m.objectives.length
      ? '<div class="panel"><h3 class="panel-title">🎯 What you\'ll be able to do</h3>' +
        m.objectives.map((o, i) =>
          '<div class="coach-row"><label class="coach-check" style="flex:1"><input type="checkbox" data-action="toggle-section" data-idx="' + i + '" ' + (st.sections[i] ? 'checked' : '') + '/> <span>' + inlineMd(o) + '</span></label></div>'
        ).join('') + '</div>'
      : '';

    const setup = g.setupDocUrl
      ? '<a class="btn small" href="' + esc(g.setupDocUrl) + '" target="_blank" rel="noopener">⚙ Environment setup</a>'
      : '<span class="pill">⚙ Setup guide — link to be added</span>';

    // If the companion/ historical layer specifically calls out this module,
    // surface it here — the actual content lives once, on the guide page.
    const companionNote = m.companionLinks?.length
      ? '<div class="panel" style="border-color:var(--accent-dim,#3a3f52)"><h3 class="panel-title">📜 Historical context for this module</h3>' +
        m.companionLinks.map((l) => '<p class="panel-hint" style="margin:0 0 6px">' + inlineMd(l.description) + '</p>').join('') +
        '<a class="btn small" data-guide="' + g.slug + '">See the guide\'s own Historical Context panel →</a></div>'
      : '';

    document.getElementById('main').innerHTML =
      '<div class="wrap">' +
      '<div class="crumbs"><a data-nav="home">Home</a> / <a data-guide="' + g.slug + '">' + esc(shortLang(g)) + '</a> / ' + esc(m.title) + '</div>' +
      '<h1 class="page-title">' + (m.kind === 'assessment' ? '' : 'Module ' + m.moduleNumber + ' · ') + esc(m.title) + '</h1>' +
      '<div style="margin-bottom:8px">' + setup + '</div>' +
      companionNote +
      objectivesList +
      '<div class="content">' + m.html + '</div>' +
      '<div class="panel"><h3 class="panel-title">🧭 Coach me (Socratic)</h3>' +
        '<p class="panel-hint">Copies a prompt for <em>your</em> LLM that makes it ask you questions instead of writing the code. Run the code in your own editor.</p>' +
        coachRows + '</div>' +
      quiz + refl + capNote +
      '<div class="module-foot">' +
        (st.completed
          ? '<span class="pill green">✓ Module complete</span> <button class="btn" data-action="uncomplete">Mark incomplete</button>'
          : '<button class="btn primary" data-action="complete">✓ Mark module complete (+' + XP.moduleComplete + ' XP)</button>') +
        '<span class="self-mark">⏱ ' + fmtTime(st.timeMs) + ' on this module</span>' +
      '</div>' +
      '</div>';
    document.getElementById('main').scrollTop = 0;
  }

  function renderRating(r) {
    const val = draft[r.id] || 0;
    let dots = '';
    for (let i = 1; i <= r.max; i++) {
      dots += '<span class="dot ' + (i <= val ? 'on' : '') + (r.id === 'difficulty' ? ' diff' : '') + '" data-action="rate" data-id="' + r.id + '" data-val="' + i + '"></span>';
    }
    return '<div class="rating"><span class="rlabel">' + esc(r.label) + '</span>' +
      '<span class="ends">' + esc(r.lowLabel) + '</span><span class="dots">' + dots + '</span><span class="ends">' + esc(r.highLabel) + '</span></div>';
  }

  function renderThreads() {
    const items = DATA.threads.map((t) =>
      '<div class="thread-item"><h3>🧵 ' + esc(t.name) + '</h3><div class="content">' + t.html + '</div></div>'
    ).join('');
    document.getElementById('main').innerHTML =
      '<div class="wrap">' +
      '<div class="crumbs"><a data-nav="home">Home</a> / Threads</div>' +
      '<h1 class="page-title">Cross-language threads</h1>' +
      '<p class="page-sub">The same idea, traced across languages and decades. These are what make this a <em>survey</em>, not a stack of unrelated courses — and where you start noticing which way of thinking fits you. (A visual skill tree over these is the natural next build.)</p>' +
      items + '</div>';
  }

  // The full seven-era History-of-Computing document (companion/history/), parsed
  // at build time. Each doc's own internal links are pre-rewritten to hash routes
  // (#/history/... and #/guide/...) so era/reading-list/index navigation works
  // the same way clicking through the rest of the app does.
  function renderHistoryDoc(slug) {
    const h = DATA.history;
    const doc = h && h.docs.find((d) => d.slug === slug);
    if (!doc) return renderHome();
    document.getElementById('main').innerHTML =
      '<div class="wrap">' +
      '<div class="crumbs"><a data-nav="home">Home</a> / <a data-nav="history">History of Computing</a>' +
      (slug === '00-overview' ? '' : ' / ' + esc(doc.title)) + '</div>' +
      '<h1 class="page-title">' + esc(doc.title) + '</h1>' +
      '<div class="content">' + doc.html + '</div>' +
      '</div>';
    document.getElementById('main').scrollTop = 0;
  }

  // The post-transformer orchestration appendix (appendix-ai-orchestration/), parsed
  // at build time same as history/. Its own source files carry no internal nav prose
  // (unlike the era files), so prev/next here is computed from doc order, not linked
  // in the markdown itself.
  function renderAppendixDoc(slug) {
    const a = DATA.appendix;
    const idx = a ? a.docs.findIndex((d) => d.slug === slug) : -1;
    if (idx === -1) return renderHome();
    const doc = a.docs[idx];
    const prev = a.docs[idx - 1];
    const next = a.docs[idx + 1];
    const nav =
      '<div class="module-foot">' +
      (prev ? '<a class="btn small" href="#/appendix/' + prev.slug + '">← ' + esc(prev.title) + '</a>' : '<span></span>') +
      (next ? '<a class="btn small" href="#/appendix/' + next.slug + '">' + esc(next.title) + ' →</a>' : '') +
      '</div>';
    document.getElementById('main').innerHTML =
      '<div class="wrap">' +
      '<div class="crumbs"><a data-nav="home">Home</a> / <a data-nav="appendix">AI Orchestration Appendix</a>' +
      (slug === '00-overview' ? '' : ' / ' + esc(doc.title)) + '</div>' +
      '<h1 class="page-title">' + esc(doc.title) + '</h1>' +
      '<div class="content">' + doc.html + '</div>' +
      nav +
      '</div>';
    document.getElementById('main').scrollTop = 0;
  }

  // ---------- portfolio ----------
  function aptitudeSummary() {
    const rows = [];
    for (const g of GUIDES) {
      let n = 0, interest = 0, confidence = 0, difficulty = 0, timeMs = 0, done = 0, reflections = 0;
      for (const m of g.modules) {
        const st = store.modules[mkey(g.slug, m.file)];
        if (!st) continue;
        timeMs += st.timeMs || 0;
        if (st.completed) done++;
        const rf = st.reflection;
        if (rf && rf.savedAt) {
          reflections++;
          if (rf.interest) { interest += rf.interest; n++; }
          if (rf.confidence) confidence += rf.confidence;
          if (rf.difficulty) difficulty += rf.difficulty;
        }
      }
      const avgInterest = n ? interest / n : 0;
      const avgConfidence = n ? confidence / n : 0;
      const avgDifficulty = n ? difficulty / n : 0;
      rows.push({ slug: g.slug, name: shortLang(g), reflections, done, timeMs, avgInterest, avgConfidence, avgDifficulty,
        score: avgInterest + avgConfidence + done * 0.5 });
    }
    rows.sort((a, b) => b.score - a.score);
    return rows;
  }

  function buildPortfolioMarkdown() {
    const rows = aptitudeSummary();
    const engaged = rows.filter((r) => r.reflections > 0 || r.done > 0 || r.timeMs > 0);
    const top = rows.find((r) => r.reflections > 0) || engaged[0];
    let totalTime = 0, totalDone = 0, totalMods = 0;
    for (const g of GUIDES) { totalMods += g.modules.length; for (const m of g.modules) { const st = store.modules[mkey(g.slug, m.file)]; totalDone += st?.completed ? 1 : 0; totalTime += st?.timeMs || 0; } }

    let md = '# My code-rookie portfolio\n\n';
    md += '_Generated ' + new Date().toLocaleString() + ' · a survey of foundational programming languages._\n\n';
    md += '## Overview\n\n';
    md += '- **Modules completed:** ' + totalDone + ' / ' + totalMods + '\n';
    md += '- **Time invested:** ' + fmtTime(totalTime) + '\n';
    md += '- **XP / level:** ' + totalXP() + ' XP · Level ' + level(totalXP()) + '\n';
    md += '- **Longest streak recorded ending recently:** ' + computeStreak() + ' day(s)\n\n';

    md += '## Where my interest and aptitude point\n\n';
    if (top && (top.reflections > 0 || top.done > 0)) {
      md += 'Based on my own reflections (interest + confidence) and engagement, my signals point most strongly toward **' + top.name + '**';
      md += top.avgInterest ? ' (avg interest ' + top.avgInterest.toFixed(1) + '/5, confidence ' + top.avgConfidence.toFixed(1) + '/5).' : '.';
      md += ' A sensible next step is to go deeper on ' + top.name + ' beyond this survey.\n\n';
    } else {
      md += '_Not enough reflections yet to call this — complete a few module reflections and re-export._\n\n';
    }
    md += '| Language | Modules done | Time | Interest | Confidence | Difficulty |\n|---|---|---|---|---|---|\n';
    for (const r of rows) {
      md += '| ' + r.name + ' | ' + r.done + '/' + guideBySlug[r.slug].modules.length + ' | ' + fmtTime(r.timeMs) + ' | ' +
        (r.avgInterest ? r.avgInterest.toFixed(1) : '–') + ' | ' + (r.avgConfidence ? r.avgConfidence.toFixed(1) : '–') + ' | ' +
        (r.avgDifficulty ? r.avgDifficulty.toFixed(1) : '–') + ' |\n';
    }
    md += '\n';

    for (const g of GUIDES) {
      const entries = g.modules.map((m) => ({ m, st: store.modules[mkey(g.slug, m.file)] })).filter((e) => e.st && (e.st.reflection?.savedAt || e.st.completed || e.st.capstoneNote || Object.keys(e.st.quiz || {}).length));
      if (!entries.length) continue;
      md += '## ' + shortLang(g) + '\n\n';
      for (const { m, st } of entries) {
        md += '### ' + (m.kind === 'assessment' ? m.title : 'Module ' + m.moduleNumber + ' — ' + m.title) + '\n\n';
        if (st.completed) md += '- Status: **complete** · Time: ' + fmtTime(st.timeMs || 0) + '\n';
        const got = Object.values(st.quiz || {}).filter((v) => v === 'got').length;
        const rev = Object.values(st.quiz || {}).filter((v) => v === 'review').length;
        if (got || rev) md += '- Self-check: ' + got + ' got it, ' + rev + ' to review\n';
        if (st.capstoneNote) md += '- Capstone artifact: ' + st.capstoneNote + '\n';
        const rf = st.reflection;
        if (rf && rf.savedAt) {
          md += '\n';
          for (const p of DATA.reflection.prompts) if (rf[p.id]) md += '**' + p.label + '** ' + rf[p.id] + '\n\n';
          const rt = DATA.reflection.ratings.map((r) => r.label + ' ' + (rf[r.id] || '–') + '/5').join(' · ');
          md += '_' + rt + '_\n\n';
        }
      }
    }

    md += '## Suggested repo structure\n\n';
    md += 'Commit your capstone work alongside this file:\n\n```\n';
    md += 'my-code-rookie/\n  PORTFOLIO.md            <- this file\n';
    for (const g of GUIDES) md += '  ' + g.slug + '/\n    capstone-1-.../\n';
    md += '```\n\n';
    md += '## How to publish\n\n```bash\ncd my-code-rookie\ngit init && git add . && git commit -m "code-rookie portfolio"\n# then create a repo and: git remote add origin <url> && git push -u origin main\n```\n';
    return md;
  }

  function download(filename, text) {
    const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = filename; document.body.appendChild(a); a.click();
    setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 500);
  }

  function renderPortfolio() {
    const rows = aptitudeSummary();
    const top = rows.find((r) => r.reflections > 0) || rows.find((r) => r.done > 0);
    let totalTime = 0, totalDone = 0, totalMods = 0;
    for (const g of GUIDES) { totalMods += g.modules.length; for (const m of g.modules) { const st = store.modules[mkey(g.slug, m.file)]; totalDone += st?.completed ? 1 : 0; totalTime += st?.timeMs || 0; } }
    document.getElementById('main').innerHTML =
      '<div class="wrap">' +
      '<div class="crumbs"><a data-nav="home">Home</a> / Portfolio</div>' +
      '<h1 class="page-title">🎓 My portfolio</h1>' +
      '<p class="page-sub">Your work, your reflections, your direction — assembled into one markdown file you own and push to your own GitHub. This is the trophy, not a grade.</p>' +
      '<div class="panel"><h3 class="panel-title">Snapshot</h3>' +
        '<p>Modules complete: <b>' + totalDone + '/' + totalMods + '</b> · Time invested: <b>' + fmtTime(totalTime) + '</b> · <b>' + totalXP() + '</b> XP (Level ' + level(totalXP()) + ')</p>' +
        (top ? '<p>Strongest signal so far: <b>' + esc(top.name) + '</b>' + (top.avgInterest ? ' — interest ' + top.avgInterest.toFixed(1) + '/5, confidence ' + top.avgConfidence.toFixed(1) + '/5' : '') + '.</p>'
             : '<p class="empty">Complete some module reflections to reveal where your interest points.</p>') +
      '</div>' +
      '<div class="panel"><h3 class="panel-title">Export</h3>' +
        '<p class="panel-hint">Downloads <code>PORTFOLIO.md</code>: overview report, per-module reflections, capstone notes, self-check scores, a preference summary, and a suggested repo layout.</p>' +
        '<button class="btn primary" data-action="export">⬇ Export portfolio (PORTFOLIO.md)</button></div>' +
      '<div class="panel"><h3 class="panel-title">Danger zone</h3>' +
        '<p class="panel-hint">All progress lives only in this browser. Exporting first is wise.</p>' +
        '<button class="btn" data-action="reset">Reset all progress</button></div>' +
      '</div>';
  }

  // ================= EVENTS =================

  function route() {
    const r = parseHash();
    if (r.view !== 'module') stopTimer();
    renderStats();
    renderSidebar(r);
    if (r.view === 'home') renderHome();
    else if (r.view === 'guide') renderGuide(r.slug);
    else if (r.view === 'module') renderModule(r.slug, r.file);
    else if (r.view === 'threads') renderThreads();
    else if (r.view === 'history') renderHistoryDoc(r.slug);
    else if (r.view === 'appendix') renderAppendixDoc(r.slug);
    else if (r.view === 'portfolio') renderPortfolio();
    document.getElementById('app').classList.remove('menu-open');
  }

  // current context for coach lookups
  function currentCtx() {
    const r = parseHash();
    if (r.view !== 'module') return null;
    const g = guideBySlug[r.slug];
    const m = g && g.modules.find((x) => x.file === r.file);
    return g && m ? { g, m, st: moduleState(r.slug, r.file) } : null;
  }

  document.addEventListener('click', (e) => {
    const t = e.target.closest('[data-action],[data-nav],[data-guide],[data-module]');
    if (!t) return;

    if (t.dataset.nav === 'home') return go('#/');
    if (t.dataset.nav === 'threads') return go('#/threads');
    if (t.dataset.nav === 'history') return go('#/history/00-overview');
    if (t.dataset.nav === 'appendix') return go('#/appendix/00-overview');
    if (t.dataset.nav === 'portfolio') return go('#/portfolio');
    if (t.dataset.guide && !t.dataset.action) return go('#/guide/' + t.dataset.guide);
    if (t.dataset.module) { const [s, f] = t.dataset.module.split('|'); return go('#/guide/' + s + '/module/' + encodeURIComponent(f)); }

    const action = t.dataset.action;
    if (!action) return;

    if (action === 'toggle-menu') { document.getElementById('app').classList.toggle('menu-open'); return; }
    if (action === 'close-modal' || action === 'modal-backdrop') { if (action === 'modal-backdrop' && e.target !== t) return; closeModal(); return; }
    if (action === 'copy-prompt') {
      const ta = document.getElementById('prompt-text');
      ta.select(); tryClipboard(ta.value);
      try { document.execCommand('copy'); } catch {}
      toast('Copied — paste into your LLM'); return;
    }

    const ctx = currentCtx();

    if (action === 'coach' && ctx) {
      const kind = t.dataset.kind; const idx = Number(t.dataset.idx);
      let section = null, objective = null, task = null;
      if (kind === 'practice') { const pr = ctx.m.practice[idx]; section = pr.section; task = pr.text; objective = objectiveForSection(ctx.m, pr.section); }
      else if (kind === 'pitfall') { const pf = ctx.m.pitfalls[idx]; section = pf.section; task = 'This gotcha from the material — help me understand *why* it happens, don\'t just restate it: ' + pf.text; objective = objectiveForSection(ctx.m, pf.section); }
      else { task = 'Walk me through the key ideas of this module and check my understanding as we go.'; objective = ctx.m.objectives[0] || null; }
      markActiveToday(); saveStore();
      openPromptModal(buildPrompt(ctx.g, ctx.m, section, objective, task));
      return;
    }
    if (action === 'flip' && ctx) {
      const card = t.closest('.flip'); const a = card.querySelector('.a');
      a.classList.toggle('hidden');
      t.textContent = a.classList.contains('hidden') ? 'Reveal answer' : 'Hide answer';
      return;
    }
    if (action === 'mark-quiz' && ctx) {
      const n = t.dataset.n; ctx.st.quiz[n] = t.dataset.val; markActiveToday(); saveStore();
      route(); renderStats(); return;
    }
    // companion/ historical-context panel — lives on the guide page, so it doesn't
    // use `ctx` (module context); it reads the guide slug off the element instead.
    if (action === 'coach-history') {
      const g = guideBySlug[t.dataset.slug];
      if (!g?.companion) return;
      markActiveToday(); saveStore();
      openPromptModal(buildHistoryPrompt(g));
      return;
    }
    if (action === 'flip-history') {
      const card = t.closest('.flip'); const a = card.querySelector('.a');
      a.classList.toggle('hidden');
      t.textContent = a.classList.contains('hidden') ? 'Reveal answer' : 'Hide answer';
      return;
    }
    if (action === 'mark-quiz-history') {
      const hst = historyState(t.dataset.slug);
      hst.qa[t.dataset.n] = t.dataset.val; markActiveToday(); saveStore();
      route(); return;
    }
    if (action === 'toggle-practice' && ctx) {
      const i = t.dataset.idx; ctx.st.practice[i] = t.checked; markActiveToday(); saveStore(); return;
    }
    if (action === 'toggle-section' && ctx) {
      const i = t.dataset.idx; ctx.st.sections[i] = t.checked; markActiveToday(); saveStore(); renderStats(); return;
    }
    if (action === 'rate' && ctx) {
      draft[t.dataset.id] = Number(t.dataset.val);
      // persist rating immediately into (draft-backed) reflection object
      ctx.st.reflection = Object.assign({}, ctx.st.reflection, pickRatings());
      saveStore();
      renderModule(ctx.g.slug, ctx.m.file); return;
    }
    if (action === 'save-reflection' && ctx) {
      readDraftFromDom();
      ctx.st.reflection = Object.assign({}, draft, { savedAt: new Date().toISOString() });
      markActiveToday(); saveStore(); toast('Reflection saved · +' + XP.reflection + ' XP');
      renderModule(ctx.g.slug, ctx.m.file); renderStats(); return;
    }
    if (action === 'save-capstone' && ctx) {
      const ta = document.querySelector('[data-capstone]'); ctx.st.capstoneNote = ta ? ta.value : '';
      markActiveToday(); saveStore(); toast('Capstone note saved'); return;
    }
    if (action === 'complete' && ctx) {
      ctx.st.completed = true; ctx.st.completedAt = new Date().toISOString(); markActiveToday(); saveStore();
      toast('Module complete · +' + XP.moduleComplete + ' XP'); route(); return;
    }
    if (action === 'uncomplete' && ctx) { ctx.st.completed = false; saveStore(); route(); return; }
    if (action === 'export') { markActiveToday(); saveStore(); download('PORTFOLIO.md', buildPortfolioMarkdown()); toast('PORTFOLIO.md downloaded'); return; }
    if (action === 'reset') {
      if (confirm('Erase all local progress? Export your portfolio first if you want to keep it.')) {
        store = { version: 1, modules: {}, activeDays: [] }; saveStore(); toast('Progress reset'); go('#/');
      }
      return;
    }
  });

  // difficulty ratings helper: gather all ratings from draft
  function pickRatings() {
    const o = {};
    for (const r of DATA.reflection.ratings) o[r.id] = draft[r.id] || 0;
    return o;
  }
  function objectiveForSection(m, section) {
    const s = m.sections.find((x) => x.heading === section);
    return s ? s.objective : (m.objectives[0] || null);
  }
  function readDraftFromDom() {
    for (const p of DATA.reflection.prompts) {
      const ta = document.querySelector('[data-refl="' + p.id + '"]');
      if (ta) draft[p.id] = ta.value;
    }
  }

  // keep draft text in sync as the user types (so a rating click doesn't lose it)
  document.addEventListener('input', (e) => {
    const el = e.target;
    if (el.dataset && el.dataset.refl) draft[el.dataset.refl] = el.value;
  });

  document.getElementById('menu-toggle').addEventListener('click', () => {
    document.getElementById('app').classList.toggle('menu-open');
  });
  document.addEventListener('visibilitychange', () => { if (document.visibilityState !== 'visible') saveStore(); });
  window.addEventListener('beforeunload', saveStore);
  window.addEventListener('hashchange', route);

  // boot
  markActiveToday(); saveStore();
  route();
})();
